export const PERSON_TAB_CONSTANTS = {
    birthCity: 'Cidade Nascimento',
    birthCountry: 'País Nascimento',
    birthDate: 'Data Nascimento',
    birthDateErrorRequired: 'Data Nascimento é obrigatório.',
    breed: 'Raça',
    cancel: 'Cancelar',
    confirmDelete: 'Você tem certeza que deseja excluir esta pessoa?',
    cpf: 'CPF',
    cpfErrorRequired: 'CPF é obrigatório.',
    edit: 'Editar',
    errorFeedback: 'Erro interno salvando pessoa.',
    female: 'FEMININO',
    fatherName: 'Nome do Pai',
    genderType: 'Gênero',
    genderTypeErrorRequired: 'Gênero é obrigatório.',
    male: 'MASCULINO',
    maritalStatus: 'Estado Civil',
    motherName: 'Nome da Mãe',
    name: 'Nome',
    nameErrorRequired: 'Nome é obrigatório.',
    no: 'NÃO',
    personForm: 'Formulário de Pessoa',
    remove: 'Remover',
    save: 'Salvar',
    successDelete: 'Pessoa removida com sucesso.',
    successFeedback: 'Passoa salva com sucesso.',
    yes: 'SIM'
};
